services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - factory-net
    volumes:
      - sqlserver_data:/var/opt/mssql

  db-connector:
    build: .
    networks:
      - factory-net
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - sqlserver
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  sqlserver_data:

networks:
  factory-net:
    name: factory-net
    external: true